name: CI
on: push
jobs:
  auto-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: check directory
        run: |
         pwd
         ls
      - name: install poetry and check version
        run: |
         pip3 install poetry
         poetry --version
      - name: set up poetry
        run: |
         source $HOME/.poetry/env
         poetry config virtualenvs.in-project true

