name: CI
on: push
jobs:
  auto-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - run: |
         pwd
         ls
         pip3 install poetry
         poetry --version
         source $HOME/.poetry/env
         poetry config virtualenvs.in-project true
         poetry install
         poetry run poe test
        working-directory: app/

