name: CI
on: push
jobs:
  auto-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
         pwd
         ls
         poetry run poe test
        working-directory: /app

