name: CI
on: push
jobs:
  auto-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - run: |
         pwd
         ls
         curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
         echo "$HOME/.poetry/bin" >> $GITHUB_PATH
         poetry --version
         poetry install
         poetry run poe test
        working-directory: app/

